// PDF report renderer — a dumb layout engine, on purpose.
//
// ai-core's generate_report tool gathers the numbers (via the same RPCs the
// chat tools use) and hands them here ALREADY FORMATTED: every amount is a
// display string, every percentage a 0–100 number. This module never touches
// the database and never does money arithmetic — it just draws.
//
// Rendering constraints worth knowing before editing:
//   * pdf-lib's standard fonts (Helvetica) are WinAnsi-encoded. encodeText()
//     THROWS on anything outside that set (emoji, CJK, ₫ …), which would kill
//     the whole report over one character in a note — so every string is passed
//     through clean() first: diacritics folded, unknown chars become '?'.
//   * There is no text wrapping. Rows are single-line and truncated with an
//     ellipsis to fit their column (fit()).
//   * Layout is a simple y-cursor that starts a new page when a block wouldn't
//     fit (ensure()). Footers are stamped onto every page at the end, when the
//     page count is known.
import { PDFDocument, PDFFont, PDFPage, rgb, StandardFonts } from 'npm:pdf-lib@1.17.1'

// --- data contract (all display-ready) ---------------------------------------
export interface ReportSummaryRow {
  currency: string
  income: string
  spending: string
  net: string
  /** Whether net >= 0 — drives the green/red of the net figure. */
  positive: boolean
  count: number
}
export interface ReportBarRow {
  name: string
  amount: string
  /** Share of the section total, 0–100. Drives the bar width. */
  pct: number
}
export interface ReportTxRow {
  date: string
  name: string
  amount: string
}
export interface ReportBudgetRow {
  name: string
  /** e.g. "Rp 1.200.000 of Rp 1.500.000" */
  detail: string
  /** Percent of the limit used; may exceed 100. */
  pct: number
}
export interface ReportLabels {
  summary: string
  income: string
  spending: string
  net: string
  transactions: string
  categories: string
  tags: string
  top: string
  budgets: string
  /** Footer credit, e.g. "Generated by Tracr". */
  credit: string
  empty: string
}
export interface ReportData {
  title: string
  bookName: string
  period: string
  generated: string
  summary: ReportSummaryRow[]
  categories: ReportBarRow[]
  tags: ReportBarRow[]
  top: ReportTxRow[]
  budgets: ReportBudgetRow[]
  labels: ReportLabels
}

// --- palette (mirrors src/index.css light theme; print is always light) ------
const BRAND = rgb(0 / 255, 114 / 255, 188 / 255) // --primary #0072bc
const BRAND_DARK = rgb(0 / 255, 86 / 255, 143 / 255)
const INK = rgb(0.11, 0.13, 0.16)
const MUTED = rgb(0.42, 0.46, 0.52)
const LINE = rgb(0.87, 0.89, 0.92)
const SOFT = rgb(0.945, 0.965, 0.985)
const POSITIVE = rgb(0.05, 0.55, 0.35)
const NEGATIVE = rgb(0.8, 0.2, 0.18)
const AMBER = rgb(0.85, 0.55, 0.1)
const WHITE = rgb(1, 1, 1)

const A4: [number, number] = [595.28, 841.89]
const MARGIN = 48
const CONTENT_W = A4[0] - MARGIN * 2

// WinAnsi-encodable characters we keep: printable ASCII, Latin-1, and the
// Windows-1252 punctuation pdf-lib maps (dashes, curly quotes, ellipsis, €).
const WIN_OK = /[\x20-\x7E\xA0-\xFF–—‘’“”…€]/

/** Fold to WinAnsi: strip diacritics, swap narrow/thin spaces for plain ones,
 *  replace anything else (emoji, other scripts) with '?'. */
function clean(s: string): string {
  const folded = (s ?? '').normalize('NFKD').replace(/[\u0300-\u036f]/g, '')
  let out = ''
  for (const ch of folded) {
    out += ch === '\u202f' || ch === '\u2009' ? ' ' : WIN_OK.test(ch) ? ch : '?'
  }
  return out
}

/** clean() every string that will meet a font — one pass at the door, so no
 *  draw site can forget (a single emoji in a category name would throw and
 *  kill the whole report). */
function sanitize(data: ReportData): ReportData {
  const bar = (r: ReportBarRow) => ({ ...r, name: clean(r.name), amount: clean(r.amount) })
  return {
    ...data,
    title: clean(data.title),
    bookName: clean(data.bookName),
    period: clean(data.period),
    generated: clean(data.generated),
    summary: data.summary.map((s) => ({
      ...s,
      currency: clean(s.currency),
      income: clean(s.income),
      spending: clean(s.spending),
      net: clean(s.net),
    })),
    categories: data.categories.map(bar),
    tags: data.tags.map(bar),
    top: data.top.map((t) => ({ date: clean(t.date), name: clean(t.name), amount: clean(t.amount) })),
    budgets: data.budgets.map((b) => ({ ...b, name: clean(b.name), detail: clean(b.detail) })),
    labels: Object.fromEntries(
      Object.entries(data.labels).map(([k, v]) => [k, clean(String(v))]),
    ) as unknown as ReportLabels,
  }
}

/** Truncate (with '…') until the string fits maxW at the given size. */
function fit(s: string, font: PDFFont, size: number, maxW: number): string {
  if (font.widthOfTextAtSize(s, size) <= maxW) return s
  let cut = s
  while (cut.length > 1 && font.widthOfTextAtSize(`${cut}…`, size) > maxW) {
    cut = cut.slice(0, -1)
  }
  return `${cut.trimEnd()}…`
}

interface Ctx {
  doc: PDFDocument
  page: PDFPage
  y: number
  regular: PDFFont
  bold: PDFFont
}

function newPage(ctx: Ctx): void {
  ctx.page = ctx.doc.addPage(A4)
  ctx.y = A4[1] - MARGIN
}

/** Start a new page unless `height` more points still fit above the footer. */
function ensure(ctx: Ctx, height: number): void {
  if (ctx.y - height < MARGIN + 24) newPage(ctx)
}

function text(
  ctx: Ctx,
  str: string,
  x: number,
  y: number,
  size: number,
  font: PDFFont,
  color = INK,
): void {
  ctx.page.drawText(str, { x, y, size, font, color })
}

function rightText(ctx: Ctx, str: string, rightX: number, y: number, size: number, font: PDFFont, color = INK): void {
  text(ctx, str, rightX - font.widthOfTextAtSize(str, size), y, size, font, color)
}

function sectionTitle(ctx: Ctx, title: string): void {
  ensure(ctx, 46)
  ctx.y -= 26
  text(ctx, title.toUpperCase(), MARGIN, ctx.y, 10, ctx.bold, BRAND_DARK)
  ctx.y -= 8
  ctx.page.drawLine({
    start: { x: MARGIN, y: ctx.y },
    end: { x: MARGIN + CONTENT_W, y: ctx.y },
    thickness: 1,
    color: LINE,
  })
  ctx.y -= 6
}

/** One name + amount + share bar row (categories / tags). */
function barRow(ctx: Ctx, row: ReportBarRow, color = BRAND): void {
  const rowH = 26
  ensure(ctx, rowH)
  const nameW = CONTENT_W * 0.6
  text(ctx, fit(row.name, ctx.regular, 9.5, nameW), MARGIN, ctx.y - 10, 9.5, ctx.regular)
  rightText(ctx, row.amount, MARGIN + CONTENT_W, ctx.y - 10, 9.5, ctx.bold)

  const barY = ctx.y - 18
  const barW = CONTENT_W - 34
  ctx.page.drawRectangle({ x: MARGIN, y: barY, width: barW, height: 4, color: SOFT })
  const pct = Math.max(0, Math.min(100, row.pct))
  if (pct > 0) {
    ctx.page.drawRectangle({
      x: MARGIN,
      y: barY,
      width: Math.max(2, (barW * pct) / 100),
      height: 4,
      color,
    })
  }
  rightText(ctx, `${Math.round(pct)}%`, MARGIN + CONTENT_W, barY - 1, 8, ctx.regular, MUTED)
  ctx.y -= rowH
}

/** Build the whole report; returns the PDF bytes. */
export async function buildReportPdf(input: ReportData): Promise<Uint8Array> {
  const data = sanitize(input)
  const doc = await PDFDocument.create()
  doc.setTitle(data.title)
  doc.setProducer('Tracr')
  doc.setCreator('Tracr')

  const regular = await doc.embedFont(StandardFonts.Helvetica)
  const bold = await doc.embedFont(StandardFonts.HelveticaBold)
  const ctx: Ctx = { doc, page: doc.addPage(A4), y: 0, regular, bold }
  const L = data.labels

  // --- header band -----------------------------------------------------------
  const bandH = 110
  ctx.page.drawRectangle({ x: 0, y: A4[1] - bandH, width: A4[0], height: bandH, color: BRAND })
  text(ctx, 'Tracr', MARGIN, A4[1] - 46, 24, bold, WHITE)
  text(ctx, clean(data.title), MARGIN, A4[1] - 70, 13, regular, WHITE)
  text(
    ctx,
    clean(`${data.bookName}  ·  ${data.period}`),
    MARGIN,
    A4[1] - 90,
    9.5,
    regular,
    rgb(0.85, 0.93, 0.98),
  )
  ctx.y = A4[1] - bandH - 8

  // --- summary (one block of three stat columns per currency) ----------------
  sectionTitle(ctx, L.summary)
  for (const s of data.summary) {
    const blockH = 64
    ensure(ctx, blockH)
    const colW = CONTENT_W / 3
    const cells: [string, string, ReturnType<typeof rgb>][] = [
      [L.income, s.income, POSITIVE],
      [L.spending, s.spending, NEGATIVE],
      [L.net, s.net, s.positive ? POSITIVE : NEGATIVE],
    ]
    cells.forEach(([label, value, color], i) => {
      const x = MARGIN + colW * i
      ctx.page.drawRectangle({ x, y: ctx.y - 46, width: 3, height: 34, color: BRAND })
      text(ctx, label.toUpperCase(), x + 10, ctx.y - 22, 8, bold, MUTED)
      // Shrink the figure if a long amount would collide with the next column.
      const size = bold.widthOfTextAtSize(value, 13) > colW - 24 ? 10.5 : 13
      text(ctx, value, x + 10, ctx.y - 40, size, bold, color)
    })
    text(
      ctx,
      `${s.currency}  ·  ${s.count} ${L.transactions}`,
      MARGIN,
      ctx.y - 60,
      8,
      regular,
      MUTED,
    )
    ctx.y -= blockH + 6
  }

  // --- categories / tags ------------------------------------------------------
  if (data.categories.length > 0) {
    sectionTitle(ctx, L.categories)
    for (const row of data.categories) barRow(ctx, row)
  }
  if (data.tags.length > 0) {
    sectionTitle(ctx, L.tags)
    for (const row of data.tags) barRow(ctx, row, BRAND_DARK)
  }

  // --- biggest transactions ----------------------------------------------------
  if (data.top.length > 0) {
    sectionTitle(ctx, L.top)
    const dateW = 64
    const amountW = 130
    const nameW = CONTENT_W - dateW - amountW - 16
    for (let i = 0; i < data.top.length; i++) {
      const rowH = 20
      ensure(ctx, rowH)
      const tx = data.top[i]
      if (i % 2 === 1) {
        ctx.page.drawRectangle({
          x: MARGIN - 4, y: ctx.y - 15, width: CONTENT_W + 8, height: 18, color: SOFT,
        })
      }
      text(ctx, tx.date, MARGIN, ctx.y - 11, 9, regular, MUTED)
      text(ctx, fit(clean(tx.name), regular, 9.5, nameW), MARGIN + dateW + 8, ctx.y - 11, 9.5, regular)
      rightText(ctx, tx.amount, MARGIN + CONTENT_W, ctx.y - 11, 9.5, bold)
      ctx.y -= rowH
    }
  }

  // --- budgets ------------------------------------------------------------------
  if (data.budgets.length > 0) {
    sectionTitle(ctx, L.budgets)
    for (const b of data.budgets) {
      const rowH = 30
      ensure(ctx, rowH)
      const color = b.pct >= 100 ? NEGATIVE : b.pct >= 80 ? AMBER : BRAND
      text(ctx, fit(clean(b.name), regular, 9.5, CONTENT_W * 0.5), MARGIN, ctx.y - 10, 9.5, regular)
      rightText(ctx, clean(b.detail), MARGIN + CONTENT_W, ctx.y - 10, 9, regular, MUTED)
      const barY = ctx.y - 20
      const barW = CONTENT_W - 34
      ctx.page.drawRectangle({ x: MARGIN, y: barY, width: barW, height: 4, color: SOFT })
      ctx.page.drawRectangle({
        x: MARGIN,
        y: barY,
        width: Math.max(2, (barW * Math.min(100, Math.max(0, b.pct))) / 100),
        height: 4,
        color,
      })
      rightText(ctx, `${Math.round(b.pct)}%`, MARGIN + CONTENT_W, barY - 1, 8, bold, color)
      ctx.y -= rowH
    }
  }

  if (
    data.summary.length === 0 &&
    data.categories.length === 0 &&
    data.top.length === 0
  ) {
    ctx.y -= 30
    text(ctx, clean(L.empty), MARGIN, ctx.y, 11, regular, MUTED)
  }

  // --- footer on every page (page count only known now) -----------------------
  const pages = doc.getPages()
  pages.forEach((page, i) => {
    page.drawLine({
      start: { x: MARGIN, y: MARGIN - 14 },
      end: { x: A4[0] - MARGIN, y: MARGIN - 14 },
      thickness: 0.75,
      color: LINE,
    })
    page.drawText(clean(`${L.credit} · ${data.generated}`), {
      x: MARGIN, y: MARGIN - 26, size: 8, font: regular, color: MUTED,
    })
    const pageLabel = `${i + 1} / ${pages.length}`
    page.drawText(pageLabel, {
      x: A4[0] - MARGIN - regular.widthOfTextAtSize(pageLabel, 8),
      y: MARGIN - 26,
      size: 8,
      font: regular,
      color: MUTED,
    })
  })

  return await doc.save()
}
