import {
  Briefcase,
  Store,
  TrendingUp,
  Plus,
  Banknote,
  Wallet,
  Coins,
  PiggyBank,
  HandCoins,
  CircleDollarSign,
  Landmark,
  CreditCard,
  Utensils,
  Coffee,
  ShoppingCart,
  ShoppingBag,
  Car,
  Bus,
  Plane,
  Fuel,
  Receipt,
  Zap,
  Lightbulb,
  Home,
  Clapperboard,
  Gamepad2,
  Music,
  HeartPulse,
  Pill,
  Dumbbell,
  GraduationCap,
  BookOpen,
  Gift,
  Shirt,
  Smartphone,
  Wifi,
  Baby,
  Dog,
  Scale,
  Ellipsis,
  type LucideIcon,
} from 'lucide-react'

/**
 * Curated icon set for categories. Names are kebab-case to match the lucide
 * names already stored by the new-user seed (e.g. 'heart-pulse').
 */
export const CATEGORY_ICONS: { name: string; Icon: LucideIcon }[] = [
  { name: 'briefcase', Icon: Briefcase },
  { name: 'store', Icon: Store },
  { name: 'trending-up', Icon: TrendingUp },
  { name: 'banknote', Icon: Banknote },
  { name: 'wallet', Icon: Wallet },
  { name: 'coins', Icon: Coins },
  { name: 'piggy-bank', Icon: PiggyBank },
  { name: 'hand-coins', Icon: HandCoins },
  { name: 'circle-dollar-sign', Icon: CircleDollarSign },
  { name: 'landmark', Icon: Landmark },
  { name: 'credit-card', Icon: CreditCard },
  { name: 'utensils', Icon: Utensils },
  { name: 'coffee', Icon: Coffee },
  { name: 'shopping-cart', Icon: ShoppingCart },
  { name: 'shopping-bag', Icon: ShoppingBag },
  { name: 'car', Icon: Car },
  { name: 'bus', Icon: Bus },
  { name: 'plane', Icon: Plane },
  { name: 'fuel', Icon: Fuel },
  { name: 'receipt', Icon: Receipt },
  { name: 'zap', Icon: Zap },
  { name: 'lightbulb', Icon: Lightbulb },
  { name: 'home', Icon: Home },
  { name: 'clapperboard', Icon: Clapperboard },
  { name: 'gamepad-2', Icon: Gamepad2 },
  { name: 'music', Icon: Music },
  { name: 'heart-pulse', Icon: HeartPulse },
  { name: 'pill', Icon: Pill },
  { name: 'dumbbell', Icon: Dumbbell },
  { name: 'graduation-cap', Icon: GraduationCap },
  { name: 'book-open', Icon: BookOpen },
  { name: 'gift', Icon: Gift },
  { name: 'shirt', Icon: Shirt },
  { name: 'smartphone', Icon: Smartphone },
  { name: 'wifi', Icon: Wifi },
  { name: 'baby', Icon: Baby },
  { name: 'dog', Icon: Dog },
  { name: 'scale', Icon: Scale },
  { name: 'plus', Icon: Plus },
  { name: 'ellipsis', Icon: Ellipsis },
]

export const ICON_MAP: Record<string, LucideIcon> = Object.fromEntries(
  CATEGORY_ICONS.map(({ name, Icon }) => [name, Icon]),
)
